### ISSUE TITLE
On Android Error

### ISSUE THREAD

**Issue by sgatibaru** [aksalj/africastalking-java#1]
Im getting an error in line 46 of the gradle file indicating ::

> Error:(46, 0) The value of a manifest attribute must not be null (Key=Implementation-Version).
<a href="openFile:/home/sky/Documents/Projects/Android/africastalking-java/build.gradle">Open File</a>

what could i be doing wrong?

**Comment by aksalj** [comment]
For usage see [https://github.com/aksalj/africastalking-java/blob/develop/doc/ANDROID.md](https://github.com/aksalj/africastalking-java/blob/develop/doc/ANDROID.md)

The error is most probably caused by your`local.properties` file. It does not have the correct values

**Comment by okelloEnos** [comment]
The value of a manifest attribute must not be null (Key=Implementation-Version).
Open File
and the above link https://github.com/aksalj/africastalking-java/blob/develop/doc/ANDROID.md does not work
